baseURL = "https://morethanmen.org"
#baseURL = 'https://chaos46692.github.io/'
languageCode = "en-us"
title = "More than Men"
theme = "ananke"
#languageCode = "en-us"
#theme = "gohugo-theme-ananke"
#themesDir = "../.."
resourceDir = "../resources"
#googleAnalytics = "G-K89WP9NL0N"

[taxonomies]
   authors = "author"
   
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"

  [[menu.main]]
    identifier = "Harassment Policies"
    name = "Harassment Policies"
    url = "/harassment-policies"

[languages]
  [languages.en]
    title = "More than Men"
    weight = 1
    contentDir = "content/"

[params]
  favicon = "fav.ico"
  site_logo = "/MTM.png"
  description = "Welcome to More than Men"
#  facebook = ""
#  twitter = "https://twitter.com/chaos46692"
#  instagram = "https://www.instagram.com/chaos46692/"
#  youtube = ""
#  github = ""
#  gitlab = ""
#  linkedin = ""
#  mastodon = ""
#  slack = ""
#  stackoverflow = ""
#  rss = ""
#  tiktok = "https://www.tiktok.com/@chaos46692"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-blue"
  cover_dimming_class = "bg-white-10"
  featured_image = "/images/mtmheader.png"
  recent_posts_number = 12
  omit_header_text = true
  custom_css = ["css/custom.css"]
  env="production"
  recent_copy="Recent Posts"


